### ISSUE TITLE
Lazy fields are not loaded, if field is declared non-searchable

### ISSUE THREAD

**Issue by RomanKurbanov** [darrachequesne/spring-data-jpa-datatables#83] opened 2018-07-30 12:34 UTC
If we declare a field as non-searchable:

```
{
            data: 'office.city',
            render: function (data) { return data ? data : '-'; },
            searchable: false
}
```
Then lazy-loaded field (office) won't be initialised

**Comment by darrachequesne** [comment] 2023-02-13 10:11
For future readers:

The problem is that we cannot know why the field is marked as non-searchable, it might be a [rendered column](https://github.com/darrachequesne/spring-data-jpa-datatables#search-on-a-rendered-column). You can manually fetch lazy fields with an additional specification though:

```java
@RestController
public class MyController {

  @RequestMapping(value = "/entities", method = RequestMethod.GET)
  public DataTablesOutput<MyEntity> list(@Valid DataTablesInput input) {
    return myRepository.findAll(input, (root, query, criteriaBuilder) -> {
      if (query.getResultType() != Long.class) {
        root.fetch("relatedEntity", JoinType.LEFT);
      }
      return null;
    });
  }
}
```

Reference: https://github.com/darrachequesne/spring-data-jpa-datatables#fetch-lazy-fields

**Closed by darrachequesne** 2023-02-13 10:11 UTC
Labels: bug
